### ISSUE TITLE
No support for hostnames with a hypen

### ISSUE THREAD

**Issue by StephanePaulus** [isometry/docker-credential-env#2]
I am trying this credential helper with a docker repo like: `mr-artifactory.data.internal`
I think the issue is because hypens are not allowed in env variables.

So when I do `EXPORT DOCKER_mr_artifactory_data_internal_USR`, it cannot find the credentials as it doesn't match
`mr.artifactory.data.internal`

**Comment by StephanePaulus** [comment]
After looking at the code:


````
func getEnvCredentials(hostname string) (username, password string, found bool) {
	labels := strings.Split(hostname, ".")

	for i := 0; i <= len(labels); i++ {
		envUsername, envPassword := getEnvVariables(labels, i)

		if username, found = os.LookupEnv(envUsername); found {
			if password, found = os.LookupEnv(envPassword); found {
				break
			}
		}
	}
	return
}
````

The hostname is just split based on the `.` char. So in the case of the host also having a `-` it will try to find env variables with the `-` in it. In my case `DOCKER_mr-artifactory_USR`, which is not valid.  I don't want to use the catch all `DOCKER__USR' variable as this limit my choices.

**Comment by isometry** [comment]
@StephanePaulus - thanks for the bug report! What do you think would be the cleanest label transformation here? `s/-/_/g` (i.e. `DOCKER_mr_artifactory_data_internal_USR`) or `s/-//g` (i.e. `DOCKER_mrartifactory_data_internal_USR`)? I lean toward the first.

To unblock you, the workaround would be `DOCKER_data_internal_USR` to scope to all Docker registries within the `data.internal` zone.

**Comment by StephanePaulus** [comment]
@isometry I would also think the first 1 makes the most sense.
